import { describe, it, expect, vi, beforeEach } from 'vitest';
import { promises as fs } from 'node:fs';
import os from 'node:os';
import path from 'node:path';

const { root } = vi.hoisted(() => ({ root: { dir: '' } }));
vi.mock('./vault.js', () => ({ getVaultRoot: vi.fn(async () => root.dir) }));
vi.mock('./settings.js', () => ({
  getSettings: vi.fn(async () => ({ auth: { userPasswordHash: 'stored-hash', passwordHash: '' } })),
}));
vi.mock('./auth.js', () => ({
  verifyPassword: vi.fn(async (pw: string, stored: string) => pw === 'secret' && stored === 'stored-hash'),
}));

import {
  globToRegExp,
  loadLocks,
  lockFor,
  resetLockCache,
  sessionMayWrite,
  targetsOf,
} from './locks.js';

const req = (headers: Record<string, string> = {}) => ({ headers }) as never;
const writeCfg = async (cfg: unknown) => {
  await fs.mkdir(path.join(root.dir, '_system'), { recursive: true });
  await fs.writeFile(path.join(root.dir, '_system', 'locks.json'), JSON.stringify(cfg));
  resetLockCache();
};

beforeEach(async () => {
  root.dir = await fs.mkdtemp(path.join(os.tmpdir(), 'vault-locks-'));
  resetLockCache();
});

describe('globToRegExp', () => {
  it('matches a whole subtree with **', () => {
    const re = globToRegExp('relats/raw/**');
    expect(re.test('relats/raw/notes/2026-09-26-answer.md')).toBe(true);
    expect(re.test('relats/raw/daily/2026-09-25.md')).toBe(true);
    expect(re.test('relats/raw')).toBe(false); // the folder itself is not a file path
    expect(re.test('relats/rawme/notes.md')).toBe(false);
  });

  it('lets **/ match at the vault root too', () => {
    const re = globToRegExp('**/board.md');
    expect(re.test('board.md')).toBe(true);
    expect(re.test('relats/board.md')).toBe(true);
    expect(re.test('a/b/board.md')).toBe(true);
  });

  it('keeps * inside one segment and escapes regex characters', () => {
    const re = globToRegExp('_system/*.md');
    expect(re.test('_system/SCHEMA.md')).toBe(true);
    expect(re.test('_system/adr/0001-text-not-a-database.md')).toBe(false);
    expect(globToRegExp('relats/reviews/2026-09.md').test('relats/reviews/2026-09.md')).toBe(true);
    expect(globToRegExp('relats/reviews/2026-09.md').test('relats/reviews/2026X09xmd')).toBe(false);
  });

  it('is case-insensitive, like the vaults it protects', () => {
    expect(globToRegExp('relats/RAW/**').test('relats/raw/x.md')).toBe(true);
  });
});

describe('loadLocks', () => {
  it('returns an empty, permissive config when there is no locks file', async () => {
    const cfg = await loadLocks();
    expect(cfg.locked).toEqual([]);
    expect(cfg.unlock).toBe('confirm');
    expect(await lockFor('relats/raw/x.md')).toBeNull();
  });

  it('reads the rules and the unlock mode, and ignores junk', async () => {
    await writeCfg({
      locked: [{ glob: 'relats/raw/**', reason: 'frozen' }, { nope: true }, 'x'],
      unlock: 'password',
    });
    const cfg = await loadLocks();
    expect(cfg.locked).toEqual([{ glob: 'relats/raw/**', reason: 'frozen' }]);
    expect(cfg.unlock).toBe('password');
  });

  it('falls back to no locks when the file is unreadable', async () => {
    await fs.mkdir(path.join(root.dir, '_system'), { recursive: true });
    await fs.writeFile(path.join(root.dir, '_system', 'locks.json'), '{ not json');
    resetLockCache();
    expect((await loadLocks()).locked).toEqual([]);
  });
});

describe('lockFor', () => {
  it('returns the first matching rule with its reason', async () => {
    await writeCfg({
      locked: [
        { glob: 'relats/raw/**', reason: 'Frozen evidence — ask the agent for a new snapshot.' },
        { glob: '**/board.md', reason: 'Generated by the agent.' },
      ],
    });
    expect((await lockFor('relats/raw/notes/x.md'))?.reason).toBe(
      'Frozen evidence — ask the agent for a new snapshot.',
    );
    expect((await lockFor('relats/board.md'))?.reason).toBe('Generated by the agent.');
    expect(await lockFor('relats/tasks/x.md')).toBeNull();
  });
});

describe('targetsOf', () => {
  it('collects every path a write touches, from body and query', () => {
    expect(targetsOf({ body: { path: 'a.md' } } as never)).toEqual(['a.md']);
    expect(targetsOf({ body: { from: 'a.md', to: '/b.md' } } as never)).toEqual(['a.md', 'b.md']);
    expect(targetsOf({ body: { dir: 'relats/raw' }, query: {} } as never)).toEqual(['relats/raw']);
    expect(targetsOf({ body: {}, query: { path: 'x.md' } } as never)).toEqual(['x.md']);
    expect(targetsOf({ body: { paths: ['a.md', 'b.md'] } } as never)).toEqual(['a.md', 'b.md']);
    expect(targetsOf({ body: {} } as never)).toEqual([]);
  });
});

describe('sessionMayWrite', () => {
  const locked = { locked: [{ glob: 'relats/raw/**', reason: 'Frozen evidence.' }] };

  it('allows anything not locked', async () => {
    await writeCfg(locked);
    expect(await sessionMayWrite(req(), 'relats/tasks/x.md')).toEqual({ ok: true });
  });

  it('refuses a locked path and explains why', async () => {
    await writeCfg({ ...locked, unlock: 'confirm' });
    expect(await sessionMayWrite(req(), 'relats/raw/daily/2026-09-25.md')).toEqual({
      ok: false,
      reason: 'Frozen evidence.',
    });
  });

  it('honours the unlock header in confirm mode only', async () => {
    await writeCfg({ ...locked, unlock: 'confirm' });
    expect(await sessionMayWrite(req({ 'x-unlock-locked': '1' }), 'relats/raw/x.md')).toEqual({ ok: true });

    await writeCfg({ ...locked, unlock: 'off' });
    expect((await sessionMayWrite(req({ 'x-unlock-locked': '1' }), 'relats/raw/x.md')).ok).toBe(false);
  });

  it('requires the operator password in password mode', async () => {
    await writeCfg({ ...locked, unlock: 'password' });
    const wrong = await sessionMayWrite(
      req({ 'x-unlock-locked': '1', 'x-unlock-password': 'nope' }),
      'relats/raw/x.md',
    );
    expect(wrong.ok).toBe(false);
    expect(wrong.reason).toContain('password');
    expect(
      (await sessionMayWrite(req({ 'x-unlock-locked': '1', 'x-unlock-password': 'secret' }), 'relats/raw/x.md')).ok,
    ).toBe(true);
    // the header alone never opens a password lock
    expect((await sessionMayWrite(req({ 'x-unlock-locked': '1' }), 'relats/raw/x.md')).ok).toBe(false);
  });
});
